version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src
      - ../config:/app/config
    environment:
      - MONGODB_URL=mongodb://admin:secret@mongodb:27017
      - DB_NAME=football_news
      - ENVIRONMENT=development
    depends_on:
      - mongodb

  etl:
    build:
      context: ..
      dockerfile: docker/Dockerfile.etl
    volumes:
      - ../src:/app/src
      - ../config:/app/config
      - ../data:/app/data
    environment:
      - MONGODB_URL=mongodb://admin:secret@mongodb:27017
      - DB_NAME=football_news
      - ENVIRONMENT=development
    depends_on:
      - mongodb

volumes:
  mongodb_data: 