name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt
        pip install pytest pytest-cov flake8 black isort
    
    - name: Check code formatting
      run: |
        black --check src/
        isort --check-only src/
    
    - name: Lint with flake8
      run: |
        flake8 src/ --count --max-line-length=100 --statistics
    
    - name: Run tests with pytest
      env:
        MONGODB_URL: mongodb://localhost:27017
        DB_NAME: football_news_test
      run: |
        pytest tests/ --cov=src/ --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 